server:
  port: 8080

spring:
  application:
    name: resource-server

  security:
    oauth2:
      resourceserver:
        jwt:
          keySetURI: http://localhost:9000/oauth2/jwks

logging:
  level:
    org:
      springframework:
        security: trace
