spring:
  application:
    name: authorization-server

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      authorizationserver:
        issuer-uri:
          - http://localhost:8080

#  security:
#    oauth2:
#      authorizationserver:
#        client:
#          public-client:
#            registration:
#              client-id: "public-client"
#              client-authentication-methods:
#                - "none"
#              authorization-grant-types:
#                - "authorization_code"
#              redirect-uris:
#                - "http://127.0.0.1:4200"
#              scopes:
#                - "openid"
#                - "profile"
#            require-authorization-consent: true
#            require-proof-key: true
#          registered-clients:
#            registration:
#              client-id: "my-client-id"
#              client-secret: "{noop}my-client-secret"
#              authorization-grant-types:
#                - "authorization_code"
#              redirect-uris:
#                - "http://localhost:8081/login/oauth2/code/my-client"
#              scopes:
#                - "read"
#                - "write"
#            require-authorization-consent: true
#            require-proof-key: true

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    sql: debug
    org:
      springframework:
        security:
          trace