spring:
  application:
    name: authorization-server

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      authorizationserver:
        registered-clients:
          my-client:
            client-id: my-client-id
            client-secret: "{noop}my-client-secret"
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/my-client"
            scope: read, write

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    sql: debug
