spring:
  application:
    name: authorization-server

server:
  port: 9000
  error:
    include-message: always

logging:
  level:
    org:
      springframework:
        security:
          oauth2: trace