server:
  port: 8081

spring:
  application:
    name: client

  security:
    oauth2:
      client:
        registration:
          auth-server:
            provider: auth-server
            client-id: client
            client-name: client
            client-secret: secret
            scope:
              - openid
              - profile
              - read
              - write
            authorization-grant-type:
              - refresh_token
              - authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/auth-server"
            client-authentication-method:
              - client_secret_basic
        provider:
          auth-server:
            issuer-uri: http://localhost:9000

logging:
  level:
    org:
      springframework:
        security:
          oauth2: trace
