server:
  port: 8081

spring:
  application:
    name: client

  security:
    oauth2:
      client:
        registration:
          oidc-client:
            provider: spring
            client-id: client
            client-name: oidc-client
            client-secret: secret
            scope:
              - openid
              - profile
              - read
              - write
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/oidc-client
#            client-authentication-method:
#              - client_secret_basic
        provider:
          spring:
            issuer-uri: http://localhost:9000

logging:
  level:
    org:
      springframework:
        security:
          oauth2: trace
