server:
  port: 8081

spring:
  application:
    name: client

  security:
    oauth2:
      client:
        registration:
          client:
#            provider: client
            client-id: client
            client-name: client
            client-secret: secret
            scope:
              - openid
#              - profile
#              - read
#              - write
            authorization-grant-type: authorization_code
#            authorization-grant-type: client_credentials
#              - refresh_token
#              - client_credentials
            redirect-uri: "http://localhost:8081/login/oauth2/code/client"
            client-authentication-method:
              - client_secret_basic
#        provider:
#          client:
#            authorization-uri: http://localhost:9000/oauth2/authorize
#            token-uri: http://localhost:9000/oauth2/token
#            user-info-uri: http://localhost:9000/userinfo
#            issuer-uri: http://localhost:9000